export const blogs = [
    {
      id: 1,
      title: 'Global Pazara Açılmak: İlk Adımlar ve Stratejiler',
      author: 'Buğrahan Arıcı',
      date: '10/03/2025',
      content: '../../contents/1.md',
      imageUrl: '/ContentImage/1.jpg',
      authorImage: '/Team/bugrahan.jpeg',
      time: '4 Dakikalık Okuma',
      category: 'Pazarlama',
      isPopular: true,
    },
    {
      id: 2,
      title: 'Güçlü Bir Marka Hikayesi Yaratmak: Doğru Stratejiler',
      author: 'Rafet Nuriyev',
      date: '12/03/2025',
      content: '../../contents/2.md',
      imageUrl: '/ContentImage/2.jpg',
      authorImage: '/Team/rafet.jpeg',
      time: '6 Dakikalık Okuma',
      category: 'Pazarlama',
      isPopular: true,
    },
  ];